# site settings
title: Purva
subtitle: Computational Analyst
email: purva.informatik@gmail.com
description: Aspiring Data Scientist<br />with a thrill for life.
baseurl: "/website" # the subpath of your site, e.g. /blog
url: "https://purva117.github.io/" # the base hostname & protocol for your site
author:
street_address: 
city: Dresden
state: Saxony,
zip_code:
country: Germany
phone: +49 179 4157537

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Purva117
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/purvapatel117/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
